version: '3'

services:
  queueserver:
    build:
      context: .
      dockerfile: images/profile/Containerfile
      args:
        PIXI_ENV: qs
    image: haxpes-queueserver:latest

  gui:
    build:
      context: .
      dockerfile: images/profile/Containerfile
      args:
        PIXI_ENV: gui
    image: haxpes-gui:latest

  sim:
    build:
      context: .
      dockerfile: images/profile/Containerfile
      args:
        PIXI_ENV: sim
    image: haxpes-sim:latest
