[configuration]
baseline = ["manipulators", "mirrors", "blconf"]
has_slits = false
has_motorized_samples = true
has_motorized_eref = false
has_polarization = false

[detector_sets.default]
primary = ""
normalization = ""
reference = ""

[devices]

[settings]
startup_modules = ["nbs_bl.startup", "haxpes.startup"]
beamline = ["sst2", "sst1"]
suspenders = ["haxpes-suspenders"]
plan_decorators = ["haxpes-shutter"]

[settings.plans]
xps = ["xps_regions.toml"]
xas = ["xas_regions.toml"]

[settings.redis.md]
host = "info.sst.nsls2.bnl.gov"
prefix = "haxpes-"

[settings.redis.info]
host = "info.sst.nsls2.bnl.gov"
prefix = "haxpes-"
# port = 60737
db = 6

[settings.tiled_writer]
enabled = true
profile = "nsls2"
api_key_env = "TILED_BLUESKY_WRITING_API_KEY_HAXPES"
subscribe_method = "post_document"

[settings.kafka]
name = "haxpes"
